// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtLQafENrMyYVj8y_FaouvGFJFz7cFMSg',
    appId: '1:146037806208:web:5991773176b4ab3cdd0265',
    messagingSenderId: '146037806208',
    projectId: 'mediaplayerwithpg',
    authDomain: 'mediaplayerwithpg.firebaseapp.com',
    storageBucket: 'mediaplayerwithpg.appspot.com',
    measurementId: 'G-6L3J8LJWDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8zAbkg2ezgADuZh24QoR6_jf4ILaZXE0',
    appId: '1:146037806208:android:c2f83efc5b3eee15dd0265',
    messagingSenderId: '146037806208',
    projectId: 'mediaplayerwithpg',
    storageBucket: 'mediaplayerwithpg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoQ5QDz0tB2HADWivhbJoyF_GWdsUn-RY',
    appId: '1:146037806208:ios:cf194a74e2d2640cdd0265',
    messagingSenderId: '146037806208',
    projectId: 'mediaplayerwithpg',
    storageBucket: 'mediaplayerwithpg.appspot.com',
    iosClientId: '146037806208-r54923mpfrniv11ilu256a9nuh8ipc6s.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicMix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoQ5QDz0tB2HADWivhbJoyF_GWdsUn-RY',
    appId: '1:146037806208:ios:e637dcb27d67fa64dd0265',
    messagingSenderId: '146037806208',
    projectId: 'mediaplayerwithpg',
    storageBucket: 'mediaplayerwithpg.appspot.com',
    iosClientId: '146037806208-3ivn95uak310kquad8rnhpajhj9vcne3.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicMix.RunnerTests',
  );
}
/*
* Platform  Firebase App Id
* web       1:146037806208:web:5991773176b4ab3cdd0265
* android   1:146037806208:android:c2f83efc5b3eee15dd0265
* ios       1:146037806208:ios:cf194a74e2d2640cdd0265
* macos     1:146037806208:ios:e637dcb27d67fa64dd0265
*/